name: Clang

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build with Clang
      run: clang++ -std=c++17 -I"include" ./src/main.cpp
